development:
  sessions:
    default:
      database: saltside_development
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
test:
  sessions:
    default:
      database: saltside_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
